import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:new_launcher/action.dart';
import 'package:new_launcher/data.dart';
import 'package:new_launcher/provider.dart';
import 'package:provider/provider.dart';

GitIgnoreModel gitIgnoreModel = GitIgnoreModel();

MyProvider providerGitIgnoreGenerator = MyProvider(
    name: "GitIgnore",
    provideActions: _provideActions,
    initActions: _initActions,
    update: _update);

Future<void> _provideActions() async {
  Global.addActions([
    MyAction(
      name: 'GitIgnore Generator',
      keywords: 'gitignore git ignore template generate language framework',
      action: () => gitIgnoreModel.refresh(),
      times: List.generate(24, (index) => 0),
    ),
  ]);
}

Future<void> _initActions() async {
  gitIgnoreModel.init();
  Global.infoModel.addInfoWidget(
      "GitIgnore",
      ChangeNotifierProvider.value(
          value: gitIgnoreModel,
          builder: (context, child) => GitIgnoreCard()),
      title: "GitIgnore Generator");
}

Future<void> _update() async {
  gitIgnoreModel.refresh();
}

enum GitIgnoreCategory {
  languages,
  frameworks,
  editors,
  operatingSystems,
  other,
}

class GitIgnoreTemplate {
  final String name;
  final GitIgnoreCategory category;
  final String content;

  const GitIgnoreTemplate({
    required this.name,
    required this.category,
    required this.content,
  });
}

const List<GitIgnoreTemplate> gitIgnoreTemplates = [
  GitIgnoreTemplate(
    name: 'Flutter',
    category: GitIgnoreCategory.frameworks,
    content: '# Flutter/Dart/Pub related\n**/doc/api/\n.dart_tool/\n.flutter-plugins\n.flutter-plugins-dependencies\n**/generated_plugin_registrant.dart\n.packages\n.pub-cache/\n.pub/\nbuild/\nflutter_*.png\n\n# Android related\n**/android/**/gradle-wrapper.jar\n**/android/.gradle\n**/android/captures/\n**/android/gradlew\n**/android/gradlew.bat\n**/android/local.properties\n**/android/**/GeneratedPluginRegistrant.java\n**/android/key.properties\n*.keystore\n*.jks\n\n# iOS/macOS related\n**/ios/**/*.mode1v3\n**/ios/**/*.mode2v3\n**/ios/**/*.moved-aside\n**/ios/**/*.pbxuser\n**/ios/**/*.perspectivev3\n**/ios/**/*sync/\n**/ios/**/.sconsign.dblite\n**/ios/**/.tags*\n**/ios/**/.vagrant/\n**/ios/**/DerivedData/\n**/ios/**/Icon?\n**/ios/**/Pods/\n**/ios/**/.symlinks/\n**/ios/**/profile\n**/ios/**/xcuserdata\n**/ios/.generated/\n**/ios/Flutter/App.framework\n**/ios/Flutter/Flutter.framework\n**/ios/Flutter/Flutter.podspec\n**/ios/Flutter/Generated.xcconfig\n**/ios/Flutter/app.flx\n**/ios/Flutter/app.zip\n**/ios/Flutter/engine\n**/ios/Flutter/flutter_assets/\n**/ios/Flutter/flutter_export_environment.sh\n**/ios/ServiceDefinitions.json\n**/macos/Flutter/GeneratedPluginRegistrant.swift\n**/macos/Flutter/ephemeral/\n\n# Web related\nlib/generated_plugin_registrant.dart\n\n# Coverage\ncoverage/\n\n# Exceptions to above rules.\n!**/ios/**/default.mode1v3\n!**/ios/**/default.mode2v3\n!**/ios/**/default.pbxuser\n!**/ios/**/default.perspectivev3',
  ),
  GitIgnoreTemplate(
    name: 'Dart',
    category: GitIgnoreCategory.languages,
    content: '# Files and directories created by pub\n.dart_tool/\n.packages\nbuild/\npubspec.lock  # Except for application packages\n\n# Directory created by dartdoc\ndoc/api/\n\n# IDE related\n.idea/\n.vscode/\n*.iml',
  ),
  GitIgnoreTemplate(
    name: 'Python',
    category: GitIgnoreCategory.languages,
    content: '# Byte-compiled / optimized / DLL files\n__pycache__/\n*.py[cod]\n*\$py.class\n\n# C extensions\n*.so\n\n# Distribution / packaging\n.Python\nbuild/\ndevelop-eggs/\ndist/\ndownloads/\neggs/\n.eggs/\nlib/\nlib64/\nparts/\nsdist/\nvar/\nwheels/\npip-wheel-metadata/\nshare/python-wheels/\n*.egg-info/\n.installed.cfg\n*.egg\nMANIFEST\n\n# PyInstaller\n*.manifest\n*.spec\n\n# Installer logs\npip-log.txt\npip-delete-this-directory.txt\n\n# Unit test / coverage reports\nhtmlcov/\n.tox/\n.nox/\n.coverage\n.coverage.*\n.cache\nnosetests.xml\ncoverage.xml\n*.cover\n*.py,cover\n.hypothesis/\n.pytest_cache/\n\n# Translations\n*.mo\n*.pot\n\n# Environments\n.env\n.venv\nenv/\nvenv/\nENV/\nenv.bak/\nvenv.bak/\n\n# Spyder project settings\n.spyderproject\n.spyproject\n\n# Rope project settings\n.ropeproject\n\n# mkdocs documentation\n/site\n\n# mypy\n.mypy_cache/\n.dmypy.json\ndmypy.json\n\n# Pyre type checker\n.pyre/\n\n# Jupyter Notebook\n.ipynb_checkpoints',
  ),
  GitIgnoreTemplate(
    name: 'Node',
    category: GitIgnoreCategory.frameworks,
    content: '# Logs\nlogs\n*.log\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\n\n# Runtime data\npids\n*.pid\n*.seed\n*.pid.lock\n\n# Directory for instrumented libs generated by jscoverage/JSCover\nlib-cov\n\n# Coverage directory used by tools like istanbul\ncoverage\n*.lcov\n\n# nyc test coverage\n.nyc_output\n\n# Grunt intermediate storage\n.grunt\n\n# Bower dependency directory\nbower_components\n\n# node-waf configuration\n.lock-wscript\n\n# Compiled binary addons\nbuild/Release\n\n# Dependency directories\nnode_modules/\njspm_packages/\n\n# TypeScript v1 declaration files\ntypings/\n\n# TypeScript cache\n*.tsbuildinfo\n\n# Optional npm cache directory\n.npm\n\n# Optional eslint cache\n.eslintcache\n\n# Optional REPL history\n.node_repl_history\n\n# Output of npm pack\n*.tgz\n\n# Yarn Integrity file\n.yarn-integrity\n\n# dotenv environment variables file\n.env\n.env.test\n\n# parcel-bundler cache\n.cache\n.parcel-cache\n\n# Next.js build output\n.next\n\n# Nuxt.js build / generate output\n.nuxt\ndist\n\n# Gatsby files\n.cache/\npublic\n\n# vuepress build output\n.vuepress/dist\n\n# Serverless directories\n.serverless/\n\n# FuseBox cache\n.fusebox/\n\n# DynamoDB Local files\n.dynamodb/\n\n# TernJS port file\n.tern-port',
  ),
  GitIgnoreTemplate(
    name: 'Java',
    category: GitIgnoreCategory.languages,
    content: '# Compiled class file\n*.class\n\n# Log file\n*.log\n\n# BlueJ files\n*.ctxt\n\n# Mobile Tools for Java (J2ME)\n.mtj.tmp/\n\n# Package Files\n*.jar\n*.war\n*.nar\n*.ear\n*.zip\n*.tar.gz\n*.rar\n\n# virtual machine crash logs\nhs_err_pid*\n\n# Maven\ntarget/\npom.xml.tag\npom.xml.releaseBackup\npom.xml.versionsBackup\npom.xml.next\nrelease.properties\ndependency-reduced-pom.xml\nbuildNumber.properties\n.mvn/timing.properties\n.mvn/wrapper/maven-wrapper.jar\n\n# Gradle\n.gradle/\nbuild/\n!gradle/wrapper/gradle-wrapper.jar',
  ),
  GitIgnoreTemplate(
    name: 'C++',
    category: GitIgnoreCategory.languages,
    content: '# Prerequisites\n*.d\n\n# Compiled Object files\n*.slo\n*.lo\n*.o\n*.obj\n\n# Precompiled Headers\n*.gch\n*.pch\n\n# Compiled Dynamic libraries\n*.so\n*.dylib\n*.dll\n\n# Fortran module files\n*.mod\n*.smod\n\n# Compiled Static libraries\n*.lai\n*.la\n*.a\n*.lib\n\n# Executables\n*.exe\n*.out\n*.app\n\n# CMake\nCMakeCache.txt\nCMakeFiles/\ncmake_install.cmake\ninstall_manifest.txt',
  ),
  GitIgnoreTemplate(
    name: 'Rust',
    category: GitIgnoreCategory.languages,
    content: '# Generated by Cargo\nCargo.lock\ntarget/\n\n# Backup files\n**/*.rs.bk\n\n# IDE\n.idea/\n.vscode/',
  ),
  GitIgnoreTemplate(
    name: 'Go',
    category: GitIgnoreCategory.languages,
    content: '# Binaries for programs and plugins\n*.exe\n*.exe~\n*.dll\n*.so\n*.dylib\n\n# Test binary, built with go test -c\n*.test\n\n# Output of the go coverage tool\n*.out\n\n# Dependency directories\nvendor/\n\n# Go workspace file\ngo.work',
  ),
  GitIgnoreTemplate(
    name: 'Swift',
    category: GitIgnoreCategory.languages,
    content: '# Xcode\nbuild/\n*.pbxuser\n!default.pbxuser\n*.mode1v3\n!default.mode1v3\n*.mode2v3\n!default.mode2v3\n*.perspectivev3\n!default.perspectivev3\nxcuserdata/\n*.xccheckout\n*.moved-aside\nDerivedData/\n*.hmap\n*.ipa\n*.dSYM.zip\n*.dSYM\n\n# CocoaPods\nPods/\n\n# Carthage\nCarthage/Build/\n\n# fastlane\nfastlane/report.xml\nfastlane/Preview.html\nfastlane/screenshots/**/*.png\nfastlane/test_output',
  ),
  GitIgnoreTemplate(
    name: 'Kotlin',
    category: GitIgnoreCategory.languages,
    content: '# Compiled class file\n*.class\n\n# Log file\n*.log\n\n# BlueJ files\n*.ctxt\n\n# Mobile Tools for Java (J2ME)\n.mtj.tmp/\n\n# Package Files\n*.jar\n*.war\n*.nar\n*.ear\n*.zip\n*.tar.gz\n*.rar\n\n# virtual machine crash logs\nhs_err_pid*\n\n# Gradle\n.gradle/\nbuild/\n!gradle/wrapper/gradle-wrapper.jar\n\n# IntelliJ\n.idea/\n*.iml\nout/\n\n# Kotlin\n*.kotlin_module',
  ),
  GitIgnoreTemplate(
    name: 'React',
    category: GitIgnoreCategory.frameworks,
    content: '# Dependencies\n/node_modules\n/.pnp\n.pnp.js\n\n# Testing\n/coverage\n\n# Production\n/build\n\n# Misc\n.DS_Store\n.env.local\n.env.development.local\n.env.test.local\n.env.production.local\n\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*',
  ),
  GitIgnoreTemplate(
    name: 'Vue',
    category: GitIgnoreCategory.frameworks,
    content: '# Dependencies\nnode_modules\n\n# Build output\ndist\n\n# Logs\nlogs\n*.log\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\n\n# Editor directories and files\n.idea\n.vscode\n*.suo\n*.ntvs*\n*.njsproj\n*.sln\n*.sw?\n\n# OS\n.DS_Store\nThumbs.db',
  ),
  GitIgnoreTemplate(
    name: 'Angular',
    category: GitIgnoreCategory.frameworks,
    content: '# Compiled output\n/dist\n/tmp\n/out-tsc\n/bazel-out\n\n# Node\n/node_modules\nnpm-debug.log\nyarn-error.log\n\n# IDE\n/.idea\n.project\n.classpath\n.c9/\n*.launch\n.settings/\n*.sublime-workspace\n\n# IDE - VSCode\n.vscode/*\n!.vscode/settings.json\n!.vscode/tasks.json\n!.vscode/launch.json\n!.vscode/extensions.json\n\n# Misc\n/.sass-cache\n/connect.lock\n/coverage\n/libpeerconnection.log\ntestem.log\n/typings\n\n# System Files\n.DS_Store\nThumbs.db',
  ),
  GitIgnoreTemplate(
    name: 'NextJS',
    category: GitIgnoreCategory.frameworks,
    content: '# dependencies\n/node_modules\n/.pnp\n.pnp.js\n\n# testing\n/coverage\n\n# next.js\n/.next/\n/out/\n\n# production\n/build\n\n# misc\n.DS_Store\n*.pem\n\n# debug\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\n\n# local env files\n.env*.local\n\n# vercel\n.vercel\n\n# typescript\n*.tsbuildinfo\nnext-env.d.ts',
  ),
  GitIgnoreTemplate(
    name: 'Svelte',
    category: GitIgnoreCategory.frameworks,
    content: '# Dependencies\nnode_modules/\n\n# Build output\n.svelte-kit/\ndist/\nbuild/\n\n# Environment files\n.env\n.env.*\n!.env.example\n\n# IDE\n.idea/\n.vscode/\n\n# OS\n.DS_Store\nThumbs.db\n\n# Logs\n*.log',
  ),
  GitIgnoreTemplate(
    name: 'Laravel',
    category: GitIgnoreCategory.frameworks,
    content: '/vendor\n/node_modules\nHomestead.yaml\nHomestead.json\n.env\n.phpunit.result.cache\n\n# Compiled files\n/public/build\n/public/dist\n/public/storage\n/public/hot\n\n# Laravel IDE helper\n_ide_helper.php\n_ide_helper_models.php\n.phpstorm.meta.php\n\n# Storage and logs\n/storage/*.key\n/storage/framework/sessions/*\n/storage/framework/views/*\n/storage/framework/cache/*\n/storage/logs/*\n\n# Bootstrap\n/bootstrap/cache/*.php',
  ),
  GitIgnoreTemplate(
    name: 'Django',
    category: GitIgnoreCategory.frameworks,
    content: '# Byte-compiled / optimized / DLL files\n__pycache__/\n*.py[cod]\n\n# C extensions\n*.so\n\n# Distribution / packaging\n.Python\nbuild/\ndevelop-eggs/\ndist/\ndownloads/\neggs/\n.eggs/\nlib/\nlib64/\nparts/\nsdist/\nvar/\nwheels/\n*.egg-info/\n.installed.cfg\n*.egg\n\n# PyInstaller\n*.manifest\n*.spec\n\n# Installer logs\npip-log.txt\npip-delete-this-directory.txt\n\n# Unit test / coverage reports\nhtmlcov/\n.tox/\n.coverage\n.coverage.*\n.cache\nnosetests.xml\ncoverage.xml\n\n# Django\n*.log\nlocal_settings.py\ndb.sqlite3\nmedia/\n\n# Virtual environments\n.env\n.venv\nenv/\nvenv/\nENV/',
  ),
  GitIgnoreTemplate(
    name: 'Spring',
    category: GitIgnoreCategory.frameworks,
    content: '# Compiled class file\n*.class\n\n# Log file\n*.log\n\n# Package Files\n*.jar\n*.war\n*.nar\n*.ear\n*.zip\n*.tar.gz\n*.rar\n\n# Maven\ntarget/\n\n# Gradle\n.gradle/\nbuild/\n!gradle/wrapper/gradle-wrapper.jar\n\n# Spring Boot\nspring-boot-devtools.properties\n\n# IDE\n.idea/\n*.iml\n.project\n.classpath\n.settings/',
  ),
  GitIgnoreTemplate(
    name: 'Ruby',
    category: GitIgnoreCategory.languages,
    content: '*.gem\n*.rbc\n/.config\n/coverage/\n/InstalledFiles\n/pkg/\n/spec/reports\n/spec/examples.txt\n/test/tmp\n/test/version_tmp\n/tmp\n\n# Used by dotenv library\n.env\n\n# Documentation cache and generated output\n/.yardoc/\n/_yardoc/\n/doc/\n/rdoc\n\n# Bundler\n/.bundle\n/vendor/bundle\n/lib/bundler/man/\n\n# Rubygems\n*.gem\n\n# RVM\n.rvmrc\n\n# JRuby\n.ruby-version\n.ruby-gemset',
  ),
  GitIgnoreTemplate(
    name: 'Rails',
    category: GitIgnoreCategory.frameworks,
    content: '# See https://help.github.com/articles/ignoring-files for more about ignoring files.\n#\n# If you find yourself ignoring temporary files generated by your text editor\n# or operating system, you probably want to add a global ignore instead:\n#   git config --global core.excludesfile ~/.gitignore_global\n\n# Ignore bundler config.\n/.bundle\n\n# Ignore the default SQLite database.\n/db/*.sqlite3\n/db/*.sqlite3-journal\n\n# Ignore all logfiles and tempfiles.\n/log/*\n/tmp/*\n!/log/.keep\n!/tmp/.keep\n\n# Ignore pidfiles, but keep the directory.\n/tmp/pids/*\n!/tmp/pids/\n!/tmp/pids/.keep\n\n# Ignore uploaded files in development.\n/storage/*\n!/storage/.keep\n\n# Ignore master key for decrypting credentials and more.\n/config/master.key\n/config/credentials.yml.enc\n\n# Ignore node_modules\n/node_modules\n\n# Ignore yarn files\n/yarn.lock\n.yarn-integrity',
  ),
  GitIgnoreTemplate(
    name: 'PHP',
    category: GitIgnoreCategory.languages,
    content: '# Composer\n/vendor\ncomposer.lock\n\n# PHPUnit\n/phpunit.xml\n.phpunit.result.cache\n\n# Build artifacts\n/build\n/dist\n\n# IDE\n.idea/\n.vscode/\n*.sublime-project\n*.sublime-workspace\n\n# OS\n.DS_Store\nThumbs.db\n\n# Logs\n*.log\n\n# Cache\n.cache/\ntmp/',
  ),
  GitIgnoreTemplate(
    name: 'CSharp',
    category: GitIgnoreCategory.languages,
    content: '# Build results\n[Dd]ebug/\n[Rr]elease/\nx64/\n[Bb]in/\n[Oo]bj/\n\n# Visual Studio\n.vs/\n*.suo\n*.user\n*.userosscache\n*.sln.docstates\n\n# NuGet\npackages/\n*.nupkg\n\n# Rider\n.idea/\n\n# User-specific files\n*.rsuser\n*.suo\n*.user\n*.userosscache',
  ),
  GitIgnoreTemplate(
    name: 'VisualStudio',
    category: GitIgnoreCategory.editors,
    content: '# Build results\n[Dd]ebug/\n[Dd]ebugPublic/\n[Rr]elease/\n[Rr]eleases/\nx64/\nx86/\n[Ww][Ii][Nn]32/\n[Aa][Rr][Mm]/\n[Aa][Rr][Mm]64/\nbld/\n[Bb]in/\n[Oo]bj/\n[Ll]og/\n[Ll]ogs/\n\n# Visual Studio 2015/2017 cache/options directory\n.vs/\n\n# MSTest test Results\n[Tt]est[Rr]esult*/\n[Bb]uild[Ll]og.*\n\n# NuGet Packages\n*.nupkg\n*.snupkg\n**/[Pp]ackages/*\npackages/\n\n# Visual Studio cache files\n*.ilk\n*.meta\n*.obj\n*.iobj\n*.pch\n*.pdb\n*.ipdb\n*.pgc\n*.pgd\n*.rsp\n*.sbr\n*.tlb\n*.tli\n*.tlh\n*.tmp\n*.tmp_proj\n*_wpftmp.csproj\n*.log\n*.vspscc\n*.vssscc\n.builds\n*.pidb\n*.svclog\n*.scc\n\n# Chutzpah Test files\n_Chutzpah*\n\n# Visual C++ cache files\nipch/\n*.aps\n*.ncb\n*.opendb\n*.opensdf\n*.sdf\n*.cachefile\n*.VC.db\n*.VC.VC.opendb\n\n# Visual Studio profiler\n*.psess\n*.vsp\n*.vspx\n*.sap\n\n# TFS 2012 Local Workspace\n\$tf/\n\n# Guidance Automation Toolkit\n*.gpState\n\n# ReSharper is a .NET coding add-in\n_ReSharper*/\n*.[Rr]e[Ss]harper\n*.DotSettings.user\n\n# TeamCity is a build add-in\n_TeamCity*\n\n# DotCover is a Code Coverage Tool\n*.dotCover\n\n# AxoCover is a Code Coverage Tool\n.axoCover/*\n!.axoCover/settings.json\n\n# Coverlet is a cross platform Code Coverage Tool\ncoverage*.json\ncoverage*.xml\ncoverage*.info\n\n# Visual Studio code coverage results\n*.coverage\n*.coveragexml\n\n# NCrunch\n_NCrunch_*\n.*crunch*.local.xml\nnCrunchTemp_*\n\n# MightyMoose\n*.M MightyMoose.config\n\n# WebWorkbench\n.sass-cache/\n\n# Installshield output folder\n[Ee]xpress/\n\n# DocProject is a documentation generator add-in\nDocProject/buildhelp/\nDocProject/Help/*.HxT\nDocProject/Help/*.HxC\nDocProject/Help/*.HxHp\nDocProject/Help/*.HxHc\nDocProject/Help/*.HxTl\nDocProject/Help/*.HxTs\nDocProject/Help/*.HxToc\nDocProject/Help/*.HxTocL\nDocProject/Help/*.HxK\nDocProject/Help/*.HxD\nDocProject/Help/*.HxKs\nDocProject/Help/*.HxHk\nDocProject/Help/*.HxDt\nDocProject/Help/*.HxHt\n\n# Click-Once directory\npublish/\n\n# Publish Web Output\n*.[Pp]ublish.xml\n*.pubxml\n*.pubxml.user\n\n# Microsoft Azure Web App publish settings\nPublishScripts/\n\n# NuGet Packages\n*.nupkg\n*.snupkg\n**/[Pp]ackages/*\n!**/[Pp]ackages/build/\n*.nuget.props\n*.nuget.targets\n\n# NuGet Symbol Packages\n*.symbols.nupkg\n\n# Chutzpah Test files\n_Chutzpah*\n\n# Visual C++ cache files\nipch/\n\n# Others\n*.dbmdl\n*.jfm\n*.pfx\n*.publishsettings\norleans.codegen.cs\n\n# Windows Store app package directories and files\nAppPackages/\nBundleArtifacts/\nPackage.StoreAssociation.xml\n_pkginfo.txt\n*.appx\n*.appxbundle\n*.appxupload\n\n# Visual Studio cache files\n*.[Cc]ache\n!?*.[Cc]ache/\n\n# Others\nClientBin/\n~\$*\n*~\n*.dbmdl\n*.dbproj.schemaview\n*.jfm\n*.pfx\n*.publishsettings\nproject.lock.json\nproject.fragment.lock.json\nartifacts/\n\n# SQL Server files\n*.mdf\n*.ldf\n*.ndf\n\n# Business Intelligence projects\n*.rdl.data\n*.bim.layout\n*.bim.settings\n\n# Microsoft Fakes\nFakesAssemblies/\n\n# Node.js Tools for Visual Studio\n.ntvs_analysis.dat\nnode_modules/\n\n# Visual Studio 6 build log\n*.plg\n\n# Visual Studio 6 workspace options file\n*.opt\n\n# Visual Studio 6 auto-generated workspace file\n*.vbw\n\n# Visual Studio LightSwitch build output\n**/*.HTMLClient/GeneratedArtifacts\n**/*.DesktopClient/GeneratedArtifacts\n**/*.DesktopClient/ModelManifest.xml\n**/*.Server/GeneratedArtifacts\n**/*.Server/ModelManifest.xml\n_Pvt_Extensions\n\n# Paket dependency manager\n.paket/paket.exe\npaket-files/\n\n# FAKE - F# Make\n.fake/\n\n# CodeRush personal settings\n.cr/personal\n\n# Python Tools for Visual Studio (PTVS)\n__pycache__/\n*.pyc\n\n# Cake - NuGet packages\ntools/**\n!tools/packages.config\n\n# Tabs Studio\n*.tss\n\n# Telerik JustMock configuration file\n*.jmconfig\n\n# BizTalk build output\n*.btp.cs\n*.btm.cs\n*.odx.cs\n*.xsd.cs\n\n# OpenCover UI analysis results\nOpenCover/\n\n# Azure Stream Analytics local run output\nASALocalRun/\n\n# MSBuild Binary and Structured Log\n*.binlog\n\n# NVidia Nsight GPU debugger configuration file\n*.nvuser\n\n# MFractors (Xamarin productivity tool) working folder\n.mfractor/\n\n# Local History for Visual Studio\n.localhistory/\n\n# BeatPulse healthcheck temp database\nhealthchecksdb\n\n# Backup folder for Package Reference Convert tool in Visual Studio 2017\nMigrationBackup/\n\n# Ionide (cross platform F# VS Code tools) working folder\n.ionide/',
  ),
  GitIgnoreTemplate(
    name: 'VSCode',
    category: GitIgnoreCategory.editors,
    content: '# VS Code specific\n.vscode/*\n!.vscode/settings.json\n!.vscode/tasks.json\n!.vscode/launch.json\n!.vscode/extensions.json\n!.vscode/*.code-snippets\n\n# Local History for Visual Studio Code\n.localhistory/\n\n# History for Visual Studio Code\n.history/',
  ),
  GitIgnoreTemplate(
    name: 'IntelliJ',
    category: GitIgnoreCategory.editors,
    content: '# Covers JetBrains IDEs: IntelliJ, RubyMine, PhpStorm, AppCode, PyCharm, CLion, Android Studio, WebStorm and Rider\n\n# User-specific stuff\n.idea/**/workspace.xml\n.idea/**/tasks.xml\n.idea/**/usage.statistics.xml\n.idea/**/dictionaries\n.idea/**/shelf\n\n# AWS User-specific\n.idea/**/aws.xml\n\n# Generated files\n.idea/**/contentModel.xml\n\n# Sensitive or high-churn files\n.idea/**/dataSources/\n.idea/**/dataSources.ids\n.idea/**/dataSources.local.xml\n.idea/**/sqlDataSources.xml\n.idea/**/dynamic.xml\n.idea/**/uiDesigner.xml\n.idea/**/dbnavigator.xml\n\n# Gradle\n.idea/**/gradle.xml\n.idea/**/libraries\n\n# Gradle and Maven with auto-import\n.idea/artifacts\n.idea/compiler.xml\n.idea/jarRepositories.xml\n.idea/modules.xml\n.idea/*.iml\n.idea/modules\n*.iml\n*.ipr\n\n# CMake\ncmake-build-*/\n\n# Mongo Explorer plugin\n.idea/**/mongoSettings.xml\n\n# File-based project format\n*.iws\n\n# IntelliJ\nout/\n\n# mpeltonen/sbt-idea plugin\n.idea_modules/\n\n# JIRA plugin\natlassian-ide-plugin.xml\n\n# Cursive Clojure plugin\n.idea/replstate.xml\n\n# SonarLint plugin\n.idea/sonarlint/\n\n# Crashlytics plugin (for Android Studio and IntelliJ)\ncom_crashlytics_export_strings.xml\ncrashlytics.properties\ncrashlytics-build.properties\nfabric.properties\n\n# Editor-based Rest Client\n.idea/httpRequests\n\n# Android studio 3.1+ serialized cache file\n.idea/caches/build_file_checksums.ser',
  ),
  GitIgnoreTemplate(
    name: 'SublimeText',
    category: GitIgnoreCategory.editors,
    content: '# Cache files for Sublime Text\n*.tmlanguage.cache\n*.tmPreferences.cache\n*.stTheme.cache\n\n# Workspace files are user-specific\n*.sublime-workspace\n\n# Project files should be checked into the repository\n*.sublime-project\n\n# SFTP configuration file\nsftp-config.json\nsftp-config-alt*.json\n\n# Package control specific files\nPackageControl.last-run\nPackageControl.ca-list\nPackageControl.ca-bundle\nPackageControl.system-ca-bundle\nPackageControl.user-ca-bundle\n\n# ST3\noscrypto-ca-bundle.crt\noscrypto-ca-bundle.cnf',
  ),
  GitIgnoreTemplate(
    name: 'Vim',
    category: GitIgnoreCategory.editors,
    content: '# Swap\n[._]*.s[a-v][a-z]\n[._]*.sw[a-p]\n[._]s[a-v][a-z]\n[._]sw[a-p]\n\n# Session\nSession.vim\nSessionx.vim\n\n# Temporary\n.netrwhist\n*~\n# Auto-generated tag files\ntags\n# Persistent undo\n[._]*.un',
  ),
  GitIgnoreTemplate(
    name: 'Emacs',
    category: GitIgnoreCategory.editors,
    content: '# -*- mode: gitignore; -*-\n*~\n\\#*\\#\n/.emacs.desktop\n/.emacs.desktop.lock\n*.elc\nauto-save-list\ntramp\n.\\#*\n\n# Org-mode\n.org-id-locations\n*_archive\n\n# flymake-mode\n*_flymake.*\n\n# eshell files\n/eshell/history\n/eshell/lastdir\n\n# elpa packages\n/elpa/\n\n# reftex-files\n*.rel\n\n# AUCTeX auto folder\n/auto/\n\n# cask packages\n.cask/\ndist/\n\n# Flycheck\nflycheck_*.el\n\n# server-emacs\n/server/\n\n# projectile\n.projectile\n\n# directory configuration\n.dir-locals.el',
  ),
  GitIgnoreTemplate(
    name: 'macOS',
    category: GitIgnoreCategory.operatingSystems,
    content: '# General\n.DS_Store\n.AppleDouble\n.LSOverride\n\n# Icon must end with two \\r\nIcon\n\n# Thumbnails\n._*\n\n# Files that might appear in the root of a volume\n.DocumentRevisions-V100\n.fseventsd\n.Spotlight-V100\n.TemporaryItems\n.Trashes\n.VolumeIcon.icns\n.com.apple.timemachine.donotpresent\n\n# Directories potentially created on remote AFP share\n.AppleDB\n.AppleDesktop\nNetwork Trash Folder\nTemporary Items\n.apdisk',
  ),
  GitIgnoreTemplate(
    name: 'Windows',
    category: GitIgnoreCategory.operatingSystems,
    content: '# Windows thumbnail cache files\nThumbs.db\nThumbs.db:encryptable\nehthumbs.db\nehthumbs_vista.db\n\n# Dump file\n*.stackdump\n\n# Folder config file\n[Dd]esktop.ini\n\n# Recycle Bin used on file shares\n\$RECYCLE.BIN/\n\n# Windows Installer files\n*.cab\n*.msi\n*.msix\n*.msm\n*.msp\n\n# Windows shortcuts\n*.lnk',
  ),
  GitIgnoreTemplate(
    name: 'Linux',
    category: GitIgnoreCategory.operatingSystems,
    content: '# temporary files which can be created if a process still has access to a file, but file is being removed or replaced\n*~\n.fuse_hidden*\n\n# KDE directory preferences\n.directory\n\n# KDE plasma desktop\n.kde4\n.plasma\n\n# temporary files which can be created if a process still has access to a file, but file is being removed or replaced\n*~\n\n# KDE directory preferences\n.directory',
  ),
  GitIgnoreTemplate(
    name: 'Archive',
    category: GitIgnoreCategory.other,
    content: '# Archive files\n*.7z\n*.rar\n*.zip\n*.gz\n*.bz2\n*.tar\n*.tgz\n*.tbz2',
  ),
  GitIgnoreTemplate(
    name: 'Backup',
    category: GitIgnoreCategory.other,
    content: '# Backup files\n*.bak\n*.backup\n*.old\n*.orig',
  ),
  GitIgnoreTemplate(
    name: 'Database',
    category: GitIgnoreCategory.other,
    content: '# Database files\n*.db\n*.sqlite\n*.sqlite3\n*.sql',
  ),
  GitIgnoreTemplate(
    name: 'Image',
    category: GitIgnoreCategory.other,
    content: '# Image files\n*.jpg\n*.jpeg\n*.png\n*.gif\n*.bmp\n*.ico\n*.svg\n*.webp\n*.tiff',
  ),
  GitIgnoreTemplate(
    name: 'Video',
    category: GitIgnoreCategory.other,
    content: '# Video files\n*.mp4\n*.avi\n*.mkv\n*.mov\n*.wmv\n*.flv\n*.webm',
  ),
  GitIgnoreTemplate(
    name: 'Audio',
    category: GitIgnoreCategory.other,
    content: '# Audio files\n*.mp3\n*.wav\n*.flac\n*.ogg\n*.aac\n*.wma',
  ),
  GitIgnoreTemplate(
    name: 'Font',
    category: GitIgnoreCategory.other,
    content: '# Font files\n*.ttf\n*.otf\n*.woff\n*.woff2\n*.eot',
  ),
];

String getGitIgnoreCategoryName(GitIgnoreCategory category) {
  switch (category) {
    case GitIgnoreCategory.languages:
      return 'Languages';
    case GitIgnoreCategory.frameworks:
      return 'Frameworks';
    case GitIgnoreCategory.editors:
      return 'Editors/IDEs';
    case GitIgnoreCategory.operatingSystems:
      return 'Operating Systems';
    case GitIgnoreCategory.other:
      return 'Other';
  }
}

Color getGitIgnoreCategoryColor(GitIgnoreCategory category, ColorScheme colorScheme) {
  switch (category) {
    case GitIgnoreCategory.languages:
      return colorScheme.primary;
    case GitIgnoreCategory.frameworks:
      return colorScheme.secondary;
    case GitIgnoreCategory.editors:
      return colorScheme.tertiary;
    case GitIgnoreCategory.operatingSystems:
      return colorScheme.primaryContainer;
    case GitIgnoreCategory.other:
      return colorScheme.surfaceContainerHighest;
  }
}

class GitIgnoreModel extends ChangeNotifier {
  bool _initialized = false;
  String _searchQuery = '';
  GitIgnoreCategory? _selectedCategory;
  final Set<String> _selectedTemplates = {};

  bool get initialized => _initialized;
  String get searchQuery => _searchQuery;
  GitIgnoreCategory? get selectedCategory => _selectedCategory;
  Set<String> get selectedTemplates => _selectedTemplates;
  List<GitIgnoreTemplate> get allTemplates => gitIgnoreTemplates;

  List<GitIgnoreTemplate> get filteredTemplates {
    var templates = gitIgnoreTemplates;

    if (_selectedCategory != null) {
      templates = templates.where((t) => t.category == _selectedCategory).toList();
    }

    if (_searchQuery.isNotEmpty) {
      final query = _searchQuery.toLowerCase();
      templates = templates.where((t) =>
        t.name.toLowerCase().contains(query) ||
        t.content.toLowerCase().contains(query)
      ).toList();
    }

    return templates;
  }

  String get generatedGitIgnore {
    if (_selectedTemplates.isEmpty) {
      return '# Select templates to generate .gitignore';
    }

    final selected = gitIgnoreTemplates.where((t) => _selectedTemplates.contains(t.name)).toList();
    final buffer = StringBuffer();

    buffer.writeln('# .gitignore generated by Flutter Launcher');
    buffer.writeln('# Combined templates: ${selected.map((t) => t.name).join(', ')}');
    buffer.writeln('');

    for (final template in selected) {
      buffer.writeln('# ===== ${template.name} =====');
      buffer.writeln(template.content);
      buffer.writeln('');
    }

    return buffer.toString();
  }

  void init() {
    if (!_initialized) {
      _initialized = true;
      Global.loggerModel.info("GitIgnore initialized", source: "GitIgnore");
      notifyListeners();
    }
  }

  void refresh() {
    notifyListeners();
  }

  void setSearchQuery(String query) {
    _searchQuery = query;
    notifyListeners();
  }

  void setSelectedCategory(GitIgnoreCategory? category) {
    _selectedCategory = category;
    notifyListeners();
  }

  void toggleTemplate(String name) {
    if (_selectedTemplates.contains(name)) {
      _selectedTemplates.remove(name);
    } else {
      _selectedTemplates.add(name);
    }
    notifyListeners();
    Global.loggerModel.info("GitIgnore template toggled: $name", source: "GitIgnore");
  }

  void clearAllTemplates() {
    _selectedTemplates.clear();
    notifyListeners();
  }

  void copyToClipboard(String text, BuildContext context) {
    Clipboard.setData(ClipboardData(text: text));
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text("Copied to clipboard"),
        duration: Duration(seconds: 2),
      ),
    );
  }
}

class GitIgnoreCard extends StatefulWidget {
  @override
  State<GitIgnoreCard> createState() => _GitIgnoreCardState();
}

class _GitIgnoreCardState extends State<GitIgnoreCard> {
  final TextEditingController _searchController = TextEditingController();

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final model = context.watch<GitIgnoreModel>();

    if (!model.initialized) {
      return Card.filled(
        color: Theme.of(context).cardColor,
        child: Padding(
          padding: EdgeInsets.all(16),
          child: CircularProgressIndicator(),
        ),
      );
    }

    return Card.filled(
      color: Theme.of(context).cardColor,
      child: Padding(
        padding: EdgeInsets.all(16),
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Icon(Icons.code, color: Theme.of(context).colorScheme.primary),
                  SizedBox(width: 8),
                  Text('GitIgnore Generator', style: Theme.of(context).textTheme.titleMedium),
                ],
              ),
              SizedBox(height: 12),
              _buildSearchField(context, model),
              SizedBox(height: 8),
              _buildCategoryFilter(context, model),
              SizedBox(height: 12),
              _buildTemplateSelection(context, model),
              if (model.selectedTemplates.isNotEmpty) ...[
                SizedBox(height: 12),
                _buildGeneratedOutput(context, model),
              ],
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSearchField(BuildContext context, GitIgnoreModel model) {
    return TextField(
      controller: _searchController,
      decoration: InputDecoration(
        hintText: 'Search templates',
        prefixIcon: Icon(Icons.search, size: 20),
        suffixIcon: _searchController.text.isNotEmpty
          ? IconButton(
              icon: Icon(Icons.clear, size: 18),
              onPressed: () {
                _searchController.clear();
                model.setSearchQuery('');
              },
            )
          : null,
        isDense: true,
        contentPadding: EdgeInsets.symmetric(horizontal: 12, vertical: 12),
        border: OutlineInputBorder(),
      ),
      onChanged: (value) => model.setSearchQuery(value),
    );
  }

  Widget _buildCategoryFilter(BuildContext context, GitIgnoreModel model) {
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: Row(
        children: [
          ActionChip(
            label: Text('All'),
            onPressed: () => model.setSelectedCategory(null),
            backgroundColor: model.selectedCategory == null
              ? Theme.of(context).colorScheme.primaryContainer
              : null,
          ),
          SizedBox(width: 4),
          ...GitIgnoreCategory.values.map((category) => Padding(
            padding: EdgeInsets.only(left: 4),
            child: ActionChip(
              label: Text(getGitIgnoreCategoryName(category)),
              onPressed: () => model.setSelectedCategory(category),
              backgroundColor: model.selectedCategory == category
                ? Theme.of(context).colorScheme.primaryContainer
                : null,
            ),
          )),
        ],
      ),
    );
  }

  Widget _buildTemplateSelection(BuildContext context, GitIgnoreModel model) {
    final templates = model.filteredTemplates;

    if (templates.isEmpty) {
      return Padding(
        padding: EdgeInsets.all(16),
        child: Text('No templates found', style: TextStyle(color: Theme.of(context).colorScheme.onSurfaceVariant)),
      );
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text('Templates (${model.selectedTemplates.length} selected)', style: TextStyle(fontWeight: FontWeight.w500)),
            if (model.selectedTemplates.isNotEmpty)
              TextButton(
                onPressed: () => model.clearAllTemplates(),
                child: Text('Clear All'),
              ),
          ],
        ),
        SizedBox(height: 8),
        Wrap(
          spacing: 8,
          runSpacing: 8,
          children: templates.take(20).map((template) => FilterChip(
            label: Text(template.name),
            selected: model.selectedTemplates.contains(template.name),
            onSelected: (selected) => model.toggleTemplate(template.name),
            avatar: Icon(_getCategoryIcon(template.category), size: 16),
          )).toList(),
        ),
      ],
    );
  }

  Widget _buildGeneratedOutput(BuildContext context, GitIgnoreModel model) {
    final output = model.generatedGitIgnore;
    final colorScheme = Theme.of(context).colorScheme;

    return Card(
      color: colorScheme.surfaceContainerHighest,
      elevation: 0,
      child: Padding(
        padding: EdgeInsets.all(12),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text('Generated .gitignore', style: TextStyle(fontWeight: FontWeight.bold)),
                Row(
                  children: [
                    IconButton(
                      icon: Icon(Icons.copy, size: 18),
                      onPressed: () => model.copyToClipboard(output, context),
                      tooltip: 'Copy to clipboard',
                    ),
                    IconButton(
                      icon: Icon(Icons.clear_all, size: 18),
                      onPressed: () => model.clearAllTemplates(),
                      tooltip: 'Clear selection',
                    ),
                  ],
                ),
              ],
            ),
            SizedBox(height: 8),
            Container(
              constraints: BoxConstraints(maxHeight: 200),
              child: SingleChildScrollView(
                child: SelectableText(
                  output,
                  style: TextStyle(fontSize: 12, fontFamily: 'monospace'),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  IconData _getCategoryIcon(GitIgnoreCategory category) {
    switch (category) {
      case GitIgnoreCategory.languages:
        return Icons.code;
      case GitIgnoreCategory.frameworks:
        return Icons.widgets;
      case GitIgnoreCategory.editors:
        return Icons.edit;
      case GitIgnoreCategory.operatingSystems:
        return Icons.computer;
      case GitIgnoreCategory.other:
        return Icons.folder;
    }
  }
}